name: Spit
options:
  bundleIdPrefix: com.intellieffect
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: J2Y925QHNV
    CODE_SIGN_STYLE: Automatic

targets:
  Spit:
    type: application
    platform: iOS
    sources:
      - path: Spit
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.intellieffect.spit
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: true
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Spit needs microphone access to record voice memos."
        SUPPORTS_MACCATALYST: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    entitlements:
      path: Spit/Resources/Spit.entitlements
      properties:
        com.apple.security.app-sandbox: true
    dependencies:
      - target: SpitWidget
        embed: true

  SpitWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: SpitWidget
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.intellieffect.spit.widget
        GENERATE_INFOPLIST_FILE: true
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SKIP_INSTALL: true
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
    entitlements:
      path: SpitWidget/SpitWidget.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - group.com.intellieffect.spit

schemes:
  Spit:
    build:
      targets:
        Spit: all
        SpitWidget: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
